version: "3.8"

services:
  github-sync:
    image: github-sync
    container_name: github-sync
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ~/.ssh:/root/.ssh
      - /var/run/docker.sock:/var/run/docker.sock
      - ./repos:/repos
      - ./.env:/app/.env:ro
    restart: unless-stopped


